kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: spark-worker
spec:
  replicas: 2
  selector:
    matchLabels:
      component: spark-worker
  template:
    metadata:
      labels:
        component: spark-worker
    spec:
      containers:
        - name: spark-worker
          image: gcr.io/spark-demo-266309/spark-standalone
          command: ["/bin/bash" , "/spark-worker"]
          ports:
            - containerPort: 8081
            - containerPort: 7078
              protocol: TCP            
          resources:
            requests:
              cpu: 100m